name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Setup PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: make install

      - name: Run tests with coverage
        run: make test-coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=maltoleb_python-project-83
            -Dsonar.organization=maltoleb
            -Dsonar.sources=page_analyzer
            -Dsonar.tests=tests
            -Dsonar.python.version=3.12
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.exclusions=tests/**
            -Dsonar.coverage.exclusions=tests/**